name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    
    - name: Setup NodeJs
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.15.1
        
    - name: Install Mocha and package for tests
      run: |
        npm install -g mocha;
        npm install
    
